* Free Riga Puškina ielā (P11)

Bijusī Rīgas Dzirnavnieka fabrikas katlu māja un ofiss, kas pēc gadiem
ilgas aizmirstības lēnām pārvērtusies par vietējo sociālo un kultūras
aktivitāšu centru. Šeit dienām (un naktīm) strādā dažādi mākslinieki
un organizācijas. Un runā, ka māja ir atvērta arī kaimiņiem, kas meklē
vietu, kur pulcēties un pavadīt laiku.

* "Deficīts"

Pazudušo mīļlietiņu “Nārnijas skapis”, kur saplūst
padomju pasaules mantojums un maģiski vecmāmiņu, kolekcionāru un, jo
īpaši, kaķumīļu dārgumi. Kur vēl Rīgā vienuviet atrast mazu kurpīšu un
porcelāna leļļu kolekciju, antīku preču maiņas punktu, pašataisītas
rotaslietas, mugursomas ar kaķu sejām un romantisku gleznu
reprodukcijas kaķu veidolā?

* Abrenes ielas pieturvieta

Abrenes ielas galapunkts lieliski ilustrē metaforu par transportu
satiksmi kā pilsētas asinsriti. Galapunkts kalpo kā sirds, kas palīdz
dzīt asinis uz priekšu – šoferīši atpūšas, nomaina cits citu un
turpina transporta plūsmu, no jauna uzņemot cilvēkus un nogādājot
viņus uz saviem mērķiem. Atceļā no tirgus, iekāpjot pieturu pirms
galapunkta un braucot līdz Abrenes ielai, ir iespēja garantēt, ka
mājupceļā nebūs jāstāv kājās ar iepirkumu maisiņiem.

* Latvijas Zinātņu аkadēmija

Latvijas Zinātņu akadēmija – padomju laika šarms bijušajā kolhoznieku
namā jūtams vēl šobaltdien. Zinātņu akadēmija mūsdienās uzņem ne tikai
zinātniekus. To labi var redzēt pusdienlaikā Zinātņua akadēmijas
ēdnīcā. Akadēmija ir darba vieta grāmatvežiem, redaktoriem,
dziedniekiem un skolotājiem. Te kādreiz glabājās Dainu skapis, bet
tagad telpas kļuvušas par krāsainu kapitālisma  dzītu profesiju
rasolu.

* Kurpnieka darbnīca

Runā, ka apkaimē un, iespējams, Rīgā labākā un izdevīgākā kurpnieka
darbnīca!

* Sarkanā Krusta sociālais centrs “Gaiziņš”

Dzeltenajā ēkā pie Centrāltirgus patvērumu un atbalstu rod cilvēki ar
visdažādākajiem dzīvesstāstiem. Cits nāk pēc siltiem ziemas zābakiem
vai pārtikas paciņas, cits izgulēt vakardienas reibumu, vēl kāds
saņemt padomu un kādu uzmundrinošu vārdu. Ikdiena šeit ir krāsaina,
bet, lai kādu dzīves ceļu ikviens no šejienes iemītniekiem būtu
mērojis, visus vieno vēlme būt noderīgiem un pieņemtiem.

* Pazemes gājēju tunelis zem Gogoļa ielas

Vieta, kurai ik dienas cauri izskrien simtiem cilvēku, acis pat
nepaceļot. Taču, ja uz mirkli apstājas un paraugās apkārt, var
ieraudzīt “visas Latvijas sabiedrības krāsas”, sākot ar steigas
pārņemtiem studentiem un beidzot ar ielu muzikantiem un pensionāriem,
kas tirgo pašu adītas vilnas zeķes. Tunelis lielākajai daļai cilvēku
nodrošina ērtāku un drošāku pārvietošanos, bet dažiem tā ir vieta, kur
nopelnīt trūkstošo centu maizītei vai patverties no sliktiem laika
apstākļiem.

* SIA "Organza" audumu veikals

Veca ķieģeļu siena ar askētisku norādi „Audumi” ved uz veikalu
garāmgājējiem nepamanāmā vietā, tomēr pēc pārdevējas teiktā veikalu
iecienījuši jaunie dizaineri, un tam nekad nav bijusi vajadzīga īpaša
reklāma. Te ienākot, ielas neomulību nomaina veikalā esošā miera un
vienkāršības sajūta.

* Lunchbox

Jauna vietiņa ar izdevīgu pusdienu piedāvājumu, ko saimnieks
tiešsaistē pārrauga no sava kabineta tuvējā augstceltnē.

* Rīgas Jēzus baznīca

Gandrīz 400 gadu ir pagājuši, pilsētas robežas ir mainījušās, bet
dievnams tur turpina stāvēt, nemainīgi piederot luteriskajai draudzei,
tikai šobrīd jau citā – savā ceturtajā veidolā, kā lielākā koka
baznīca Latvijā. Te senioru smaidi mijas ar mazu bērnu čalām. “Es te
nācu un nākšu. Šī ir visskaistākā baznīca. Svēta vieta.”  Tā par šo
vietu izsakās baznīcā sastapta ļoti cienījama vecuma kundze.

* Antikvaribārs “Bānūzis”

Vieta, kas ļauj tās apmeklētājiem iepazīt aizgājušo laiku artefaktus
un veldzēties taustāmās atmiņās. Tieši niansēs slēpjas šī antikvariāta
šarms, un vislabāk to var atklāt nesteidzīgi malkojot namatēva
sarūpētos dzērienus un iesaistoties improvizētā stāstu programmā pie
bāra letes. Ar saimniekiem esam vienisprātis - "Bānūzim" “zīmējas
spoža nākotne”.

* Grāmatnīca “Janus”

Liels veikals, kas slēpjas mazas un vienkāršas koka mājiņas
aizsegā. Tajā var pavadīt pat pusi dienas, iepazīstoties ar jaunāko
krievu literatūru vai savu nākamā gada horoskopu. Pārdevējas šajā
veikalā dažkārt ieņem gluži vai psihologa lomu, palīdzot cilvēkiem
atrast to, ko viņi meklē.

* Rīgas Lielās Horālās sinagogas memoriāls

Memoriāls, kurā esošie objekti, vienlaikus pieminot nāvi un dzīvību,
ir pretstatā viens otram. Automašīnu troksnis un ebreju glābēju vārdi
šeit skan skaļāk par upuru kliedzieniem. “Dzīve iet uz priekšu,”
iepazīstinot ar memoriālu, atgādina vietējais rabīns un piedāvā
iepazīties ar viņa kabinetā esošajām grāmatām par ebreju iznīcināšanu
Latvijā.

* "Igo. Akcents personībai"

No skata necila vienstāva māja patukšās Turgeņeva ielas pašā
galā. Māju ieņēmusi radoša komanda, lai dienas gaismu ieraudzītu
dažādi mūziķa Igo Fomina radīti dizaina priekšmeti. Šī mājīgā darbnīca
ieved pilnīgā Igo pasaulē, kur rodamas visas viņa mākslinieciskās
izpausmes vienuviet. "Igo. Akcents personībai" ir pavisam jauns
iemītnieks šajā kvartālā, kas rada citādu un kontrastējošu apkaimes
tēlu.

* Hanza Hotel

Neliela trīs zvaigžņu viesnīca, kas varbūt atrodas un varbūt neatrodas
Maskačkā.

* Ugunsdzēsēju depo

Priecīgi par apmeklētājiem, kuriem nekas nedeg, ugunsdzēsēji ir
pretimnākoši, laipni un labi jūt cilvēkus.

* Kafejnīca “Rozmarīns”

Pēc nosaukuma nepateiksi, ka šīs kafejnīcas interjerā dominē doriskās
un joniskās grieķu kolonnas. “Rozmarīns” ir vieta ar attieksmi, to
atklās katrs vērīgs apmeklētājs. Klusā rītā stāvot pie letes, no
virtuves dzirdamas pavāru un konditoru dzīvīgās sarunas. Pati
saimniece saka, ja cilvēks vēloties paēst, viņam te vienmēr tiks kaut
kas pasniegts - kartupeļi ar rozmarīnu, piemēram.

* Centrāltirgus

Starp pieciem pārbūvētiem cepelīnu angāriem ik dienu mutuļo garšas,
smaržas un cilvēku pūļi, kas zina, kur, kas un par cik atrodams. Te ir
sava pašsaprotama kārtība, pārdevējiem balsis skaļas un cenas - tikai
tās labākās. Katrai precei beigu beigās atrodas savs pircējs - gan
kontrabandas cigaretēm un tūristu suvenīriem, gan Ogrē audzētajām
puķēm, ko katru rītu puķu pārdevējas uz tirgu ved ar vilcienu.

* Vissvētās Dievmātes Pasludināšanas pareizticīgo baznīca

Pāri ielai pie policijas iecirkņa ēkas Gogoļa un Turgeņeva ielu
krustojumā sēž vīrs un vēro putniņus. Viņš te nāk “katru dienu -
desmit gadus jau”. Pareizticīgo krusts uztetovēts uz vidējā pirksta,
vīrietis apliecina, ka brīvdienās cilvēku nāk maz. “Bet svētku dienās,
jā – tad gan nāk.” Otrpus ielai baznīcas darbiniece gan par
apmeklētāju daudzumu nesūdzas. Un nākot ne tikai pareizticīgie, bet
arī luterāņi un katoļi. “Jo viņiem sveces tur savās baznīcās likt nav
kur, un pasūtīt lūgšanas par drošību un veselību viņi nevar. Tāpēc
viņi nāk šeit. Citās baznīcās tā neļauj, bet pie mums ļauj. Vot tā!”

* Spīķeri

Dažu gadu laikā šis sākotnēji maz zināmais kultūrpunkts ir daudz
mainījies un attīstijies. Gadsimtu senās spīķeru noliktavas no omulīgā
subkultūru nostūra pārveidojušās par ģimenei draudzīgu vietiņu, kur
bērni un jaunieši var izklaidēties labiekārtotajā laukumā, bet vecāki
pavadīt laiku kafejnīcās un salonos. Tāpat šeit joprojām mājo
kritiskie un laikmetīgie teātra uzvedumi no Dirty Deal Teatro.

* Nail Smile

Krustojumā esošs frizētavu-skaistumkopšanas salonu pāris ieintriģē ar
pašu neapzināto vienotību. Ar pieticību un atrunām pārdevēja saka, ka
par apkārtnē notiekošo neko nezina. Tomēr frizierītes pulcina
rīdziniekus no visām pilsētas malām, vienlaicīgi radot teju nemanāmu,
tomēr rajonu spilgti raksturojošu iespaidu par krievu-latviešu
līdzāspastāvēšanu.

* Kafejnīca “Sviesta pika”

Aiz privātas autostāvvietas uz Elijas un Puškina ielas stūra, kuru
gadiem pārvalda tas pats uzraugs, atrodas kafejnīca "Sviesta pika", ko
īpaši iecienījuši autoskolu instruktori. "Sviesta pikā" var ieskriet
pēc zupas, kafijas un pusdienu piedāvājuma - ir izvēle starp soļanku
un mājas soļanku.

* "Latgalīte"

No skaidu plāksnēm un plastmasas plēvēm būvētās paralēlajās realitātēs
birokrātijai ir pārāk auksti. Savas dzīves karaļi jums sagādās visu -
no akumulatora lādētāja līdz vientuļa zaldāta dienasgrāmatai. ''Tā jau
mums viss ir labi, un narkomānu te nav,'' viņš bilst un noslauka
biksēs no rokām pilošo motoreļļu.

* Apģērbu veikals

Kādreiz šeit strādāja bārs, kur vietējie pēc iedzeršanas gāja “pār
ielas ēst šašliku”, un ar apaļiem vēderiem čāpoja atpakaļ. Tā stāsta
iedzīvotāji, kuri vel joprojām ienāk aplūkot bijušās, iemīļotās
“розoвые стены”. Tagad šeit cilvēku balsis ir aizvietotas ar nemitīgu
džinsu šķirošanu. Drēbes šeit ir uzticamas un, galvenais, lētas, jo
“laiki diemžēl paliek arvien grūtāki”.

* Free Riga Turgeņeva ielas rezidence (T17)

Neuzkrītoša, teju 200 gadus veca divstāvu dzīvojamā ēka. Mājas otrais
stāvs pēc pieciem tukšiem gadiem ir ieguvis otro elpu - tur tagad
apmetušies Free Riga rezidenti. Kaimiņu uzmanību piesaista pie sētas
pieslēgtie ērmriteņi, un pamazām tiek iestaigāta taciņa, lai atvērtu
šo māju pasākumiem un jaunām iniciatīvām.
