* Free Riga Puškina ielā (P11)
Puškina iela 11

Bijusī Rīgas Dzirnavnieka fabrikas katlu māja un ofiss, kas pēc gadiem
ilgas aizmirstības lēnām pārvērtusies par vietējo sociālo un kultūras
aktivitāšu centru. Šeit dienām (un naktīm) strādā dažādi mākslinieki
un organizācijas. Un runā, ka māja ir atvērta arī kaimiņiem, kas meklē
vietu, kur pulcēties un pavadīt laiku.

* "Deficīts"
GPS 56.942117, 24.119644

Pazudušo mīļlietiņu “Nārnijas skapis”, kur saplūst
padomju pasaules mantojums un maģiski vecmāmiņu, kolekcionāru un, jo
īpaši, kaķumīļu dārgumi. Kur vēl Rīgā vienuviet atrast mazu kurpīšu un
porcelāna leļļu kolekciju, antīku preču maiņas punktu, pašataisītas
rotaslietas, mugursomas ar kaķu sejām un romantisku gleznu
reprodukcijas kaķu veidolā?

Atverot “Deficīta” durvis, tevi sagaida sludinājumu siena ar asprātīgiem izteicieniem krievu valodā, kas rada smaidu ikviena ienācēja sejā. Katrs var noplēst lapiņu, lai sev atgādinātu par vienkāršajiem dzīves prieciņiem. “Deficīts” ir unikāla vieta, kur var atrast jebko, sākot no kolekcionāru veidotām porcelāna leļļu kolekcijām līdz kaķu mugursomām un hand made rotaslietām. Īpašniece sapņo par pārmaiņām Maskavas ielas rajonā, atceroties laikus, kad Rūpniecības preču tirgus bija dzīvīgāks un arī veikalā viesu bija vairāk. “Deficīta” īpašniece uzskata, ka rajonam ir milzīgs potenciāls, kurš netiekot novērtēts sliktās reprezentācijas dēļ. Īpašnieces pieķeršanās veikalam ir daudz spēcīgāka par biznesa domāšanu. Unikālais retro veikaliņa vispusīgais piedāvājums ir radījis vairāk muzeja, nevis veikaliņa sajūtu. Piedāvājot visu, netiek piedāvāts nekas. Te pat pastāv maiņas tirgus princips - ir iespējams apamainīt savas  retro, padomju laiku mantas pret citu atstātām. “Tā ir visa mana dzīve, mans hobijs! Lai gan naudu ar šo nenopelnīsi, man prieks redzēt smaidu cilvēku sejās, piedāvāt unikālas preces! Šis veikals patīk ikvienam, varbūt, izņemot tos Stockmann cilvēkus” smejas īpašniece. 


* Abrenes ielas pieturvieta
GPS 56.945681, 24.131111

Abrenes ielas galapunkts lieliski ilustrē metaforu par transportu
satiksmi kā pilsētas asinsriti. Galapunkts kalpo kā sirds, kas palīdz
dzīt asinis uz priekšu – šoferīši atpūšas, nomaina cits citu un
turpina transporta plūsmu, no jauna uzņemot cilvēkus un nogādājot
viņus uz saviem mērķiem. Atceļā no tirgus, iekāpjot pieturu pirms
galapunkta un braucot līdz Abrenes ielai, ir iespēja garantēt, ka
mājupceļā nebūs jāstāv kājās ar iepirkumu maisiņiem.

Šķietami nebeidzamas autobusu rindas, cilvēku un transportu nepārtraukta plūsma, šoferīši, kuri dodas atputā, velkot dūmu no cigaretes vai raitā solī steidz atpakaļ pie stūres, lērums dažādu un krāšņu pašažieru, kas iekāpj vai izkāpj – šāda ainava paveras Abrenes ielas autobusu galapunktā. Par spīti spraigajai burzmai, šī vieta atstāj vientulīgu iespaidu. Pat ja visus cilvēkus šī telpa vieno kā pieturas punkts, sākums vai noslēgums ikdienas ceļā, katrs šeit ir pats par sevi. Pietura ir plaša un cilvēki labprāt izmanto telpu, lai noslēgtos un ieturētu distanci cits no cita. Šī vieta ir kā pauze cilvēka ikdienas dinamikā, kā starpposms starp nokļūšanu no viena punkta uz nākamo. 

Tieši vecāka gadu gājuma Centrāltirgus apmeklētāji ir iecienījuši Abrenes ielas galapunktu kā stratēģiski izdevīgu pieturu, ar kuru iespējams izvairīties no bariem, kas stumdās pieturā pie tirgus. Iekāpjot pieturu pirms galapunkta un braucot līdz Abrenes ielai, ir iespēja garantēt, ka mājupceļā nebūs jāstāv kājās ar iepirkumu maisiņiem. Savukārt jaunieši izbauda, ka Abrenes ielas galapunktā ir pietiekami plaši, lai varētu izvēlēties savu stūrīti nost no citiem cilvēkiem, kur justies netraucēti. Tajā pašā laikā laužu plūsma ļauj justies drošāk nekā vientuļākās pieturās. 

Šī vieta ir kā radīta introvertiem cilvēkiem – vari droši nodoties pārdomām par dzīvi, citi netraucēs un nav nepieciešams justies slikti par to, ka neiesaisties sarunās, jo neviens cits arī nevēlas iesaistīties.

* Latvijas Zinātņu аkadēmija
Latvijas Zinātņu аkadēmija

Latvijas Zinātņu akadēmija – padomju laika šarms bijušajā kolhoznieku
namā jūtams vēl šobaltdien. Zinātņu akadēmija mūsdienās uzņem ne tikai
zinātniekus. To labi var redzēt pusdienlaikā Zinātņua akadēmijas
ēdnīcā. Akadēmija ir darba vieta grāmatvežiem, redaktoriem,
dziedniekiem un skolotājiem. Te kādreiz glabājās Dainu skapis, bet
tagad telpas kļuvušas par krāsainu kapitālisma dzītu profesiju
rasolu.

* Kurpnieka darbnīca
GPS 56.941921, 24.119300

Runā, ka apkaimē un, iespējams, Rīgā labākā un izdevīgākā kurpnieka
darbnīca!

* Sarkanā Krusta sociālais centrs “Gaiziņš”
GPS 56.942063, 24.118892

Dzeltenajā ēkā pie Centrāltirgus patvērumu un atbalstu rod cilvēki ar
visdažādākajiem dzīvesstāstiem. Cits nāk pēc siltiem ziemas zābakiem
vai pārtikas paciņas, cits izgulēt vakardienas reibumu, vēl kāds
saņemt padomu un kādu uzmundrinošu vārdu. Ikdiena šeit ir krāsaina,
bet, lai kādu dzīves ceļu ikviens no šejienes iemītniekiem būtu
mērojis, visus vieno vēlme būt noderīgiem un pieņemtiem.

Šajā mājā dzīve ir raiba un negaidītu notikumu pilna. Ik dienu centrā pēc palīdzības un padoma ierodas visdažādākie cilvēki, kuru dzīvē izveidojusies smaga situācija. Darbinieki palīdz nokārtot nepieciešamos dokumentus un meklēt risinājumus dažādām dzīves situācijām. Atnākušie saņem ne tikai praktisku palīdzību, bet arī emocionālu atbalstu – arī draudzīgs sveiciens un piederības sajūta nozīmē daudz. Centrā darbojas arī naktspatversme, kuras iemītnieki strikti sadalīti trīs stāvos – pirmajā iereibušie, augstāk tie, kas skaidrā prātā. Vairums patversmes iemītnieku ir prasmīgi meistari un neatsaka palīdzību ikdienas darbos, piemēram, šo to pielabojot, notīrot sniegu vai pieskatot datortelpu.

Vispamanāmākie no centra klientiem ir bezpajumtnieki, kuri pa vienam vai mazos pulciņos sastopami apkārtnē. Viņu ikdienā liela loma ir blakus esošajam Centrāltirgum, kur var dabūt ko ēdamu un dzeramu, kā arī kādu gadījuma darbiņu. 

Sociālā centra darbu var atbalstīt, ziedojot kādu noderīgu lietu – apģērbus, apavus vai sadzīves priekšmetus. Centra darbinieki parūpēsies, lai mantas nonāktu to cilvēku rokās, kam tās visvairāk nepieciešamas.

* Pazemes gājēju tunelis zem Gogoļa ielas
GPS 56.945419, 24.119448

Vieta, kurai ik dienas cauri izskrien simtiem cilvēku, acis pat
nepaceļot. Taču, ja uz mirkli apstājas un paraugās apkārt, var
ieraudzīt “visas Latvijas sabiedrības krāsas”, sākot ar steigas
pārņemtiem studentiem un beidzot ar ielu muzikantiem un pensionāriem,
kas tirgo pašu adītas vilnas zeķes. Tunelis lielākajai daļai cilvēku
nodrošina ērtāku un drošāku pārvietošanos, bet dažiem tā ir vieta, kur
nopelnīt trūkstošo centu maizītei vai patverties no sliktiem laika
apstākļiem.

Kad laukā ir auksts, cilvēku ir mazāk un esošie vairāk steidzas garām. Ir cilvēki, kam gājēju tunelis zem Gogoļa ielas ir darba un cerību vieta. Kaprona zeķbikšu un zeķu, adītu zeķu, cimdu un šaļļu, kā arī tamborētu pašdarinājumu tirgotāji uzturas šeit pastāvīgi (pat par spīti policijas darbinieku neatlaidīgajiem mēģinājumiem viņus no šīs vietas padzīt). Tuvojoties salam, sievietes pensijas vecumā, kuras nestrādā vai nu invaliditātes vai nesekmīgu darba meklējumu dēļ, šeit cenšas pavadīt, cik vien laika spēj, lai sapelnītu uz priekšu. Katrai no viņām ir sava vieta tunelī, blakus balstiem. Šīs vietas netiek savā starpā mainītas, un, ja ieņem svešu vietu, rodas konflikti. Kā atzina divas no sievietēm, vietai, kur stāv, ir nozīme - visvairāk veicoties tām, kas stāv kādā no tuneļa galiem. Mazbērni un ģimenes ir lielākie prieki viņu dzīvēs, un jūtamas ilgas pēc tuvākajiem. Lielākoties šī distance ir piespiedu kārtā, jo līdzekļi ir pārāk ierobežoti, lai ģimeni un radiniekus apciemotu tik bieži, cik gribētos.

* SIA "Organza" audumu veikals
Puškina iela 20a

Veca ķieģeļu siena ar askētisku norādi „Audumi” ved uz veikalu
garāmgājējiem nepamanāmā vietā, tomēr pēc pārdevējas teiktā veikalu
iecienījuši jaunie dizaineri, un tam nekad nav bijusi vajadzīga īpaša
reklāma. Te ienākot, ielas neomulību nomaina veikalā esošā miera un
vienkāršības sajūta.

Veikals atrodas veco noliktavu telpās. Dzeltenīgo, apdrupušo ķieģeļu ēka ir vienkārša, gadu gaitā pielabota un pielāgota tiem, kas tur ir strādājuši. Par to, ka iekšpagalmā atrodas veikals norāda tikai liels zilganzaļš uzraksts „Audumi”, jo nekas vairāk nav vajadzīgs. Zinātāji atradīs. 

Ieejot iekšā caur mazām, nedaudz ļodzīgām durvīm, nošķind vēja zvani un paveras skats uz telpu ar arkveida griestiem, kurā ir audumu baķiem pilni plaukti. Pāris sienas un pieliekamos aizsedz aizkari, un uz durvīm ir uzraksti, ka pieņem tikai skaidru naudu. 

Uz šo vietu nāk visi Latvijas tērpu dizaineri un daži Igaunijas dizaineri, kā arī citi, kas nodarbojas ar šūšanu. Veikalam nekad nav bijusi vajadzīga reklāma.Vietējie gan reti nākot. 

Veikala darbiniece ir norobežojušies no Lastādijas, turklāt veikals šeit atrodas zemās īres dēļ. Tā drīzāk esot Maskačka – jo tālāk, jo trakāk. Lastādija vairāk ietekmējot veikalu, nekā veikals Lastādiju. Lai kā arī būtu viņa lepojas ar savu darbavietu neatkarīgi no tā, ko domā par rajonu. 

* Lunchbox
GPS 56.9418, 24.122648

Jauna vietiņa ar izdevīgu pusdienu piedāvājumu, ko saimnieks
tiešsaistē pārrauga no sava kabineta tuvējā augstceltnē.

* Rīgas Jēzus baznīca
GPS 56.94162, 24.1235

Gandrīz 400 gadu ir pagājuši, pilsētas robežas ir mainījušās, bet
dievnams tur turpina stāvēt, nemainīgi piederot luteriskajai draudzei,
tikai šobrīd jau citā – savā ceturtajā veidolā, kā lielākā koka
baznīca Latvijā. Te senioru smaidi mijas ar mazu bērnu čalām. “Es te
nācu un nākšu. Šī ir visskaistākā baznīca. Svēta vieta.”  Tā par šo
vietu izsakās baznīcā sastapta ļoti cienījama vecuma kundze.

Pretēji vispārpieņemtajiem kanoniem, Jēzus baznīcas centrālā ieeja tika būvēta nevis uz austrumiem, bet uz dienvidaustrumiem, lai būtu pretī tiem, kas nāca no pilsētas uz priekšpilsētu. Dievnama celtniecības vēstures pirmais nozīmīgākais gads ir 1638. Gandrīz 400 gadi ir pagājuši, pilsētas robežas ir mainījušās, bet dievnams te turpina stāvēt, nemainīgi piederot luteriskajai draudzei. Šī brīža baznīca ir ceturtā Jēzus baznīca šajā vietā, pārstāvot lielāko koka baznīcu Latvijā. Kāda baznīcā sastapta ļoti cienījama vecuma kundze apgalvo, ka “baznīca šeit bija un paliks mūžīgi”, lai arī kādi notikumi tai negājā un neies pāri. Pārliecība viņas balsī neliek apšaubīt viņas teikto, tieši šāds ticīgo spēks, šķiet, ir noturējis un turpina turēt šo dievnamu laika griežos. Baznīca ir iecienīta, baznīcēnu ir daudz. Svētdienas dievkalpojumus apmeklē ap 300 cilvēku, un tas vēl neesot nekas, uz Ziemassvētkiem baznīcā esot tik pilns, ka cilvēki kājās stāv. Apmeklētāji ir dažāda vecuma cilvēki, sākot ar zīdaiņiem, kas čalo baznīcas aizmugurē, un beidzot ar cienījama vecuma senioriem, te visi gaidīti.

* Antikvaribārs “Bānūzis”
GPS 56.9432628, 24.1243507

Vieta, kas ļauj tās apmeklētājiem iepazīt aizgājušo laiku artefaktus
un veldzēties taustāmās atmiņās. Tieši niansēs slēpjas šī antikvariāta
šarms, un vislabāk to var atklāt nesteidzīgi malkojot namatēva
sarūpētos dzērienus un iesaistoties improvizētā stāstu programmā pie
bāra letes. Ar saimniekiem esam vienisprātis - "Bānūzim" “zīmējas
spoža nākotne”.

* Grāmatnīca “Janus”
GPS 56.94140, 24.12273

Liels veikals, kas slēpjas mazas un vienkāršas koka mājiņas
aizsegā. Tajā var pavadīt pat pusi dienas, iepazīstoties ar jaunāko
krievu literatūru vai savu nākamā gada horoskopu. Pārdevējas šajā
veikalā dažkārt ieņem gluži vai psihologa lomu, palīdzot cilvēkiem
atrast to, ko viņi meklē.

* Rīgas Lielās Horālās sinagogas memoriāls
GPS 56.942451, 24.126339

Memoriāls, kurā esošie objekti, vienlaikus pieminot nāvi un dzīvību,
ir pretstatā viens otram. Automašīnu troksnis un ebreju glābēju vārdi
šeit skan skaļāk par upuru kliedzieniem. “Dzīve iet uz priekšu,”
iepazīstinot ar memoriālu, atgādina vietējais rabīns un piedāvā
iepazīties ar viņa kabinetā esošajām grāmatām par ebreju iznīcināšanu
Latvijā.

* "Igo. Akcents personībai"
GPS 56.940723, 24.117702

No skata necila vienstāva māja patukšās Turgeņeva ielas pašā
galā. Māju ieņēmusi radoša komanda, lai dienas gaismu ieraudzītu
dažādi mūziķa Igo Fomina radīti dizaina priekšmeti. Šī mājīgā darbnīca
ieved pilnīgā Igo pasaulē, kur rodamas visas viņa mākslinieciskās
izpausmes vienuviet. "Igo. Akcents personībai" ir pavisam jauns
iemītnieks šajā kvartālā, kas rada citādu un kontrastējošu apkaimes
tēlu.

* Hanza Hotel
GPS 56.94205, 24.123442

Neliela trīs zvaigžņu viesnīca, kas varbūt atrodas un varbūt neatrodas
Maskačkā.

* Ugunsdzēsēju depo
GPS 56.942560, 24.115759

Priecīgi par apmeklētājiem, kuriem nekas nedeg, ugunsdzēsēji ir
pretimnākoši, laipni un labi jūt cilvēkus.

* Kafejnīca “Rozmarīns”
GPS 56.939676, 24.124602

Pēc nosaukuma nepateiksi, ka šīs kafejnīcas interjerā dominē doriskās
un joniskās grieķu kolonnas. “Rozmarīns” ir vieta ar attieksmi, to
atklās katrs vērīgs apmeklētājs. Klusā rītā stāvot pie letes, no
virtuves dzirdamas pavāru un konditoru dzīvīgās sarunas. Pati
saimniece saka, ja cilvēks vēloties paēst, viņam te vienmēr tiks kaut
kas pasniegts - kartupeļi ar rozmarīnu, piemēram.

* Centrāltirgus
GPS 56.943945, 24.116780

Starp pieciem pārbūvētiem cepelīnu angāriem ik dienu mutuļo garšas,
smaržas un cilvēku pūļi, kas zina, kur, kas un par cik atrodams. Te ir
sava pašsaprotama kārtība, pārdevējiem balsis skaļas un cenas - tikai
tās labākās. Katrai precei beigu beigās atrodas savs pircējs - gan
kontrabandas cigaretēm un tūristu suvenīriem, gan Ogrē audzētajām
puķēm, ko katru rītu puķu pārdevējas uz tirgu ved ar vilcienu.

* Vissvētās Dievmātes Pasludināšanas pareizticīgo baznīca
GPS 56.943944, 24.122906

Pāri ielai pie policijas iecirkņa ēkas Gogoļa un Turgeņeva ielu
krustojumā sēž vīrs un vēro putniņus. Viņš te nāk “katru dienu -
desmit gadus jau”. Pareizticīgo krusts uztetovēts uz vidējā pirksta,
vīrietis apliecina, ka brīvdienās cilvēku nāk maz. “Bet svētku dienās,
jā – tad gan nāk.” Otrpus ielai baznīcas darbiniece gan par
apmeklētāju daudzumu nesūdzas. Un nākot ne tikai pareizticīgie, bet
arī luterāņi un katoļi. “Jo viņiem sveces tur savās baznīcās likt nav
kur, un pasūtīt lūgšanas par drošību un veselību viņi nevar. Tāpēc
viņi nāk šeit. Citās baznīcās tā neļauj, bet pie mums ļauj. Vot tā!”

* Spīķeri
GPS 56.9416366, 24.116552

Dažu gadu laikā šis sākotnēji maz zināmais kultūrpunkts ir daudz
mainījies un attīstijies. Gadsimtu senās spīķeru noliktavas no omulīgā
subkultūru nostūra pārveidojušās par ģimenei draudzīgu vietiņu, kur
bērni un jaunieši var izklaidēties labiekārtotajā laukumā, bet vecāki
pavadīt laiku kafejnīcās un salonos. Tāpat šeit joprojām mājo
kritiskie un laikmetīgie teātra uzvedumi no Dirty Deal Teatro.

* Nail Smile
GPS 56.942118, 24.122880

Krustojumā esošs frizētavu-skaistumkopšanas salonu pāris ieintriģē ar
pašu neapzināto vienotību. Ar pieticību un atrunām pārdevēja saka, ka
par apkārtnē notiekošo neko nezina. Tomēr frizierītes pulcina
rīdziniekus no visām pilsētas malām, vienlaicīgi radot teju nemanāmu,
tomēr rajonu spilgti raksturojošu iespaidu par krievu-latviešu
līdzāspastāvēšanu.

* Kafejnīca “Sviesta pika”
GPS 56.942356, 24.121587

Aiz privātas autostāvvietas uz Elijas un Puškina ielas stūra, kuru
gadiem pārvalda tas pats uzraugs, atrodas kafejnīca "Sviesta pika", ko
īpaši iecienījuši autoskolu instruktori. "Sviesta pikā" var ieskriet
pēc zupas, kafijas un pusdienu piedāvājuma - ir izvēle starp soļanku
un mājas soļanku.

* "Latgalīte"
9a Firsa Sadovnikova iela

No skaidu plāksnēm un plastmasas plēvēm būvētās paralēlajās realitātēs
birokrātijai ir pārāk auksti. Savas dzīves karaļi jums sagādās visu -
no akumulatora lādētāja līdz vientuļa zaldāta dienasgrāmatai. ''Tā jau
mums viss ir labi, un narkomānu te nav,'' viņš bilst un noslauka
biksēs no rokām pilošo motoreļļu.

* Apģērbu veikals
GPS 56.9401, 24.127702

Kādreiz šeit strādāja bārs, kur vietējie pēc iedzeršanas gāja “pār
ielas ēst šašliku”, un ar apaļiem vēderiem čāpoja atpakaļ. Tā stāsta
iedzīvotāji, kuri vel joprojām ienāk aplūkot bijušās, iemīļotās
“розoвые стены”. Tagad šeit cilvēku balsis ir aizvietotas ar nemitīgu
džinsu šķirošanu. Drēbes šeit ir uzticamas un, galvenais, lētas, jo
“laiki diemžēl paliek arvien grūtāki”.

* Free Riga Turgeņeva ielas rezidence (T17)
Turgeņeva iela 17

Neuzkrītoša, teju 200 gadus veca divstāvu dzīvojamā ēka. Mājas otrais
stāvs pēc pieciem tukšiem gadiem ir ieguvis otro elpu - tur tagad
apmetušies Free Riga rezidenti. Kaimiņu uzmanību piesaista pie sētas
pieslēgtie ērmriteņi, un pamazām tiek iestaigāta taciņa, lai atvērtu
šo māju pasākumiem un jaunām iniciatīvām.
