#!/usr/bin/env bash
shopt -s extglob
first=1
while read line; do
  if [[ $line == "* "* ]]; then
    i=$((i+1))
    read address
    if [[ $address != "" ]]; then
      if [[ $address == "GPS "* ]]; then
        coords=${address##GPS }
        echo "$line: custom coordinates $coords" >&2
      else
        echo -n "$line: geocoding $address... " >&2
        coords=$(./geocode $address)
        echo $coords >&2
      fi
      read # skip blank line
    else
      echo "**$line lacks address" >&2
      coords=
    fi
    
    [ $first ] || echo "</article>"; first=
    
    cat <<.

<article>
  <h2>
    <span class=number>$i</span>
    <span class=name>${line##\* }</span>
  </h2>
  <address><coords>$coords</coords></address>
.
    echo "  <p class=summary>"
    while read summary; do
      if [[ $summary == "" ]]; then
        break
      else
        echo "    $summary"
      fi
    done
  else
    if [[ $line == "" ]]; then
      echo "  <p>"
    else
      echo "    $line"
    fi
  fi
done

cat <<.
</article>
.
